### ISSUE TITLE
A way to open source the calendar events?

### ISSUE THREAD

**Issue by The-RedWizard** [aPeoplesCalendar/apc-web#57]
So I really like this project. Enough that I've actually used some of the information found in the repos here to make a little project called [APC-JSON](https://github.com/Hexbear-Code-Op/apc-json). 

The idea is that the events in the calendar could be stored as a JSON file, allowing people to pull that JSON file and use it in their own projects. I posted this little idea within a community I'm a part of, and we were able to build a python script that can transform the JSON event data into a .ics file, which people can then import into their calendar of choice. 

This got me browsing a lot of the events in the calendar, and I happened to notice some things that seemed odd. Tags that seemed unrelated, or some minor or major typos that could stand to be corrected. This got me thinking about ways in which we could distribute the process of editing, adding, proofreading, etc. the events in the calendar. It reminded me of [Project Gutenberg's Distributed Proofreaders Project,](https://www.pgdp.net/c/) which is how they manage to OCR old books and get the pages cleaned up without it being the job of a single group of people. You get assigned a single page of a book to check for issues and then submit your changes. 

So, if each event existed as a file format that could then be easily updated by a human, and then read and transformed by a script to be reincorporated back into the main database, that would provide a nice little feedback loop that could allow for all kinds of collaborative maintenance. That file format could be a YAML file, for example. Here is an example of what that file would look like:

```yaml
id: 66493748-24e1-48ab-aaea-2648a5f60322
title: Haitian Independence (1804)
slugTitle: haitian-independence-1804
otd: On this day in 1804, the Haitian Republic was established by self-liberated slaves, the culmination of years of violent revolt against French colonizers. More than 200,000 Haitians died in the struggle for liberation.
description: |-
  On this day in 1804, the Haitian Republic was established by self-liberated slaves, the culmination of years of violent revolt against French colonizers. More than 200,000 Haitians died in the struggle for liberation.

  The Haitian Revolution was the only uprising of enslaved people that led to the founding of a state which was both free from slavery, and ruled by non-whites and former captives.

  The revolt began on August 21st, 1791, in what was then the French colony of Saint-Domingue. Thousands of people began to kill their masters, plunge the colony into civil war.

  Within the next ten days, slaves had taken control of the entire Northern Province in an uprising of unprecedented scale. The fighting was particularly brutal, and more than 200,000 black people died in the years between the initial uprising and formal independence.

  Although Toussaint Louverture established himself as a military leader of the revolution by 1801, he died shortly before independence was won. Jean-Jacques Dessalines, his former lieutenant, became the first leader of Haiti.
imgAltText: The painting "Attack and take of the Crête-à-Pierrot" (March 24th, 1802), by Auguste Raffet [blackpast.org]
NSFW: false
imgSrc: Events/haitianRevolution.jpg
date: 1804-01-01
links:
- https://www.blackpast.org/global-african-history/haitian-revolution-1791-1804/
- https://libcom.org/library/black-jacobins-toussaint-louverture-san-domingo-revolution
- https://en.wikipedia.org/wiki/Haitian_Revolution
- https://eji.org/news/haitis-forced-payments-to-enslavers-cost-economy-21-billion-the-new-york-times-found/
tags:
- Independence
day: 1
month: 1
```
